In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

In [2]:
# read the dataframe
df = pd.read_csv("../csv/home_price_feature_selection.csv")
df.head()

,area_sqft,bedrooms,bathrooms,age_years,distance_city_km,school_rating,crime_index,parking_spaces,garden_sqft,random_noise_1,random_noise_2,sale_price
0,858,1,4,26,3.11,8,6.76,2,118,1.286842,2,361017.76
1,2844,4,3,13,16.58,7,2.81,2,20,-1.909763,48,720717.59
2,2498,5,3,11,5.39,10,8.99,3,376,-1.279497,84,733855.88
3,1872,5,4,16,6.18,10,8.31,3,409,-1.032032,34,602266.65
4,1855,2,1,29,22.50,8,4.15,0,463,-0.063320,7,431711.05

In [4]:
df.isna().sum()

area_sqft           0
bedrooms            0
bathrooms           0
age_years           0
distance_city_km    0
school_rating       0
crime_index         0
parking_spaces      0
garden_sqft         0
random_noise_1      0
random_noise_2      0
sale_price          0
dtype: int64

In [5]:
x = df.drop("sale_price", axis=1)
y = df['sale_price']
x.shape, y.shape

((500, 11), (500,))

In [6]:
from mlxtend.feature_selection import SequentialFeatureSelector as sfs
from sklearn.linear_model import LinearRegression

In [7]:
lreg = LinearRegression()
sfs1 = sfs(lreg, k_features=6, forward=True, verbose=2, scoring='neg_mean_squared_error')

In [8]:
sfs1 = sfs1.fit(x,y)

[Parallel(n_jobs=1)]: Done  11 out of  11 | elapsed:    0.0s finished

[2026-08-08 11:32:34] Features: 1/6 -- score: -5644763092.978069[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.0s finished

[2026-08-08 11:32:34] Features: 2/6 -- score: -4027197435.7416086[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:    0.0s finished

[2026-08-08 11:32:34] Features: 3/6 -- score: -2805796573.310916[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:    0.0s finished

[2026-08-08 11:32:34] Features: 4/6 -- score: -1781856555.4157803[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:    0.0s finished

[2026-08-08 11:32:34] Features: 5/6 -- score: -1331158750.6388147[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:    0.0s finished

[2026-08-08 11:32:34] Features: 6/6 -- score: -985683251.8643986

In [9]:
feat_names = list(sfs1.k_feature_names_)
print(feat_names)

['area_sqft', 'bedrooms', 'bathrooms', 'distance_city_km', 'school_rating', 'crime_index']

In [10]:
new_data = df[feat_names]
new_data['sale_price'] = df['sale_price']
new_data.head()

,area_sqft,bedrooms,bathrooms,distance_city_km,school_rating,crime_index,sale_price
0,858,1,4,3.11,8,6.76,361017.76
1,2844,4,3,16.58,7,2.81,720717.59
2,2498,5,3,5.39,10,8.99,733855.88
3,1872,5,4,6.18,10,8.31,602266.65
4,1855,2,1,22.50,8,4.15,431711.05

In [11]:
new_data.shape, df.shape

((500, 7), (500, 12))

In [12]:
# We can notice that both backward_feature_selection and forward_feature_selection selects the same features.

In [13]:
# Now with this new_data, we can continue model building using train test split